on:
  push:
    branches:
      - master
jobs:
  my_job:
    name: deploy
    runs-on: ${{ fromJSON('["ubuntu-latest", "self-hosted"]')[github.repository == 'github/docs-internal'] }}

    steps:
    - name: build and deploy 
      run: |
        ls
